basic_app/urls.py
from django.urls import path
from . import views
 # TEMPLATE TAGGING

app_name = 'basic_app'

urlpatterns = [
    path('',views.index, name= 'home'),
    path('home/',views.index, name= 'index'),
    path('other/', views.other, name='others-page'),
    path('relative/', views.relative, name='relative-path-page')
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))

]

basic_app/models.py
from django.db import models

# Create your models here.

basic_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    context_dict ={'text': 'hello world', 'number': 100}
    return render (request, 'basic_app/index.html', context_dict)

def other(request):
    return render (request, 'basic_app/other.html')

def relative(request):
    return render (request, 'basic_app/relative_url_templates.html')

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:index'%}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index'%}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:others-page'%}">OTHERS</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">

        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend-->

        {% endblock %}

    </div>
    
</body>
</html>

templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

        <h1>WELCOME O HOME</h1>
        <h2>this is index.html</h2>
        <h1>{{ text|cut:'world' }}</h1>
        <h2>{{ number|add:"99" }}</h2>

    {% endblock %}
    

templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
    {% block body_block %}

        <h1>WELCOME TO OTHERS</h1>
        <h2> This is an example of template inheritence</h2>
    {% endblock %}

templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to relative url templates</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basic_app:others-page' %}">the others page</a>
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <a href="{% url 'basic_app:index' %}">LINK TO INDEX</a>
    
    
</body>
</html>